### ISSUE TITLE
digits in the wordlist

### ISSUE THREAD

**Issue by mkrlab** [silnrsi/khmerlbdict#1]
I've seen some digits in the wordlist. Are they there on purpose? And why?
i.e. 
១០  4837
២០  3203
៣០  2544
៥០  866
៨២  87

It might not be reasonable to have numeral things in the wordlist because they are infinite and we might not want to add them all in. A few lines of code might be a better alternative.

**Comment by DidiKj** [comment]
Wich wordlist are you talking about?

I am working on editing the Bible word lists. The next version will not
have any numbers in it.

**Comment by mkrlab** [comment]
khmerlbdict https://github.com/silnrsi/khmerlbdict/src
https://github.com/silnrsi/khmerlbdict/tree/master/src/_seafreq.txt_

On Sun, Jan 17, 2016 at 11:34 AM, DidiKj notifications@github.com wrote:

> Wich wordlist are you talking about?
> 
> I am working on editing the Bible word lists. The next version will not
> have any numbers in it.
> 
> On Sun, Jan 17, 2016 at 9:20 AM, mkrlab notifications@github.com wrote:
> 
> > I've seen some digits in the wordlist. Are they there on purpose? And
> > why?
> > i.e.
> > ១០ 4837
> > ២០ 3203
> > ៣០ 2544
> > ៥០ 866
> > ៨២ 87
> > 
> > It might not be reasonable to have numeral things in the wordlist because
> > they are infinite and we might not want to add them all in. A few lines
> > of
> > code might be a better alternative.
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/silnrsi/khmerlbdict/issues/1.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/silnrsi/khmerlbdict/issues/1#issuecomment-172291386.

## 

Makara SOK

**Comment by DidiKj** [comment]
Thanks, I had expected those data to be better. I will take care of all
numbers.

Blessings,
Didi
